name: fotografias_gps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  image: ^4.6.0
  gal: ^2.3.2
  permission_handler: ^12.0.1
  get_it: ^8.0.2
  intl: ^0.19.0
  http: ^1.6.0
  path_provider: ^2.1.5
  video_player: ^2.9.2
  ffmpeg_kit_flutter_min_gpl: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
